FROM php:8.4-fpm

WORKDIR /var/www/html

# Install dependensi sistem (termasuk libicu-dev untuk ekstensi intl)
RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev \
    zip unzip libzip-dev libfreetype6-dev \
    libjpeg62-turbo-dev libgd-dev libicu-dev vim

# Bersihkan cache apt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Konfigurasi GD dan install ekstensi PHP (termasuk intl)
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-configure intl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

USER www

EXPOSE 9000
CMD ["php-fpm"]